project_id = "nhfghwwpnqoayhsitqmp"

[functions.create-razorpay-order]
verify_jwt = false

[functions.verify-razorpay-payment]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = false

[functions.daily-whatsapp-job]
verify_jwt = false
